theme = "adwaita-dark"

[editor]
lsp.display-inlay-hints = true
auto-format = true
bufferline = "always"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.select]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]